# Generated by Django 3.2.6 on 2021-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210915_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
