# Generated by Django 3.2.6 on 2021-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_email',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='nice'),
            preserve_default=False,
        ),
    ]
